GET https://hz.youcantry.me/api/

### Pinyins
GET https://hz.youcantry.me/api/pinyins/爱

### Collections
GET https://hz.youcantry.me/api/collections

### Texts
GET https://hz.youcantry.me/api/texts

###
GET https://walrus-app-we25d.ondigitalocean.app/api/collections